# Generated by Django 5.2.4 on 2025-09-17 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_project_demo_link_project_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='demo_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='tags',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='resource',
            name='resource_type',
            field=models.CharField(choices=[('notebook', 'Jupyter Notebook'), ('dataset', 'Dataset'), ('doc', 'Document'), ('other', 'Other')], default='other', max_length=20),
        ),
    ]
