# Generated by Django 5.2.7 on 2025-10-10 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_project_demo_link_project_tags_project_updated_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=200)),
                ('cover', models.ImageField(blank=True, null=True, upload_to='book_covers/')),
                ('summary_md', models.TextField(help_text='Resumen en formato Markdown')),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='book_files/')),
                ('epub_file', models.FileField(blank=True, null=True, upload_to='book_files/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
