# Generated by Django 5.2.7 on 2025-10-14 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='api_url',
            field=models.URLField(blank=True, null=True, verbose_name='URL del endpoint (si aplica)'),
        ),
        migrations.AddField(
            model_name='project',
            name='has_demo',
            field=models.BooleanField(default=False, verbose_name='¿Mostrar demo interactiva?'),
        ),
    ]
