# Generated by Django 5.2.7 on 2025-10-23 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_project_api_url_project_has_demo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
