# Generated by Django 5.2.7 on 2026-03-06 03:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_project_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Ej: Microsoft DP-100', max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='certifications/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CertUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Ej. Unidad 1', max_length=100)),
                ('title', models.CharField(help_text='Tema de la unidad', max_length=200)),
                ('summary', models.TextField(blank=True, help_text='Resumen del tema abordado en la unidad', null=True)),
                ('video_url', models.URLField(blank=True, help_text='Enlace de YouTube u otra plataforma para embeber (uno por unidad)', null=True)),
                ('flashcards_csv', models.FileField(blank=True, help_text='Sube un CSV con columnas (pregunta, respuesta) para auto-generar tarjetas al guardar en esta unidad.', null=True, upload_to='temp_csv/')),
                ('order', models.PositiveIntegerField(default=0, help_text='Orden de visualización para la certificación')),
                ('certification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units', to='main.certification')),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='CertSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('pdf_file', models.FileField(upload_to='cert_slides/')),
                ('order', models.PositiveIntegerField(default=0)),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slides', to='main.certunit')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='CertFlashcard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(help_text='Pregunta de la tarjeta')),
                ('answer', models.TextField(help_text='Respuesta de la tarjeta')),
                ('order', models.PositiveIntegerField(default=0)),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flashcards', to='main.certunit')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
